version: "3"

services:
  syncservice:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      web:
        aliases:
          - syncservice
    ports:
      - "3001:3003"
    volumes:
      - ../broclan/secrets:/usr/src/app/secrets:ro
    restart: always